Fix version and package naming
pytroll/pytroll-pps-runner pull request #13
Opened 2020-09-28 11:03 UTC by adybbroe

Change package name to nwcsafpps_runner, fix for Python3 and git versioning.

2020-09-28 12:04 UTC, mraspaud requested changes
Some inline comments. Also I do agree with some of the codefactor.io comments.

2020-09-28 12:04 UTC, mraspaud commented on nwcsafpps_runner/utils.py
> +        #LOG.debug("sending: " + str(pubmsg))
Please remove it instead of commenting it.

2020-09-28 12:39 UTC, TAlonglong reviewed
>>> n = datetime.datetime.now()
>>> n.strftime("%Y%m%dT%H%M%S")
'20200928T143910'

2020-09-28 12:47 UTC, TAlonglong reviewed
In additions to @mraspaud and some of the codecov this LGTM

2020-10-02 12:08 UTC, adybbroe commented
@mraspaud and @TAlonglong Many thanks for the useful comments. 
Code should be slightly more readable now.

2020-10-02 12:09 UTC, adybbroe commented
And, by the way, I looked at the Deep Code bot's comments and found it partly useful only. Fixed one issue. But line numbers doesn't point correctly...

2020-10-05 10:00 UTC, adybbroe commented
Thanks for your reviewing @mraspaud and @TAlonglong , do you think it looks better and ok now?

2020-10-06 07:43 UTC, mraspaud commented
@adybbroe I still think the codefactor items should be resolved

2020-10-06 09:54 UTC, adybbroe commented
Thanks @adybbroe 
Overlooked those. I have fixed all of them but 2 I believe. One I have asked your advice on, the other is the FIXME! which I don't have an answer to yet.

2020-10-06 09:58 UTC, adybbroe commented
Okay, now down to 3 issues. The two I mentioned above plus a third on "Complex code" on line 0 in `utils.py`
No idea atm what to do about that...

2020-10-06 11:32 UTC, mraspaud commented
Complex code can be helps with refactoring

2020-10-06 11:36 UTC, adybbroe commented
> Complex code can be helps with refactoring

Ok, but there was no hint. 
I can certainly look over the complexity and refactor, but not in this  PR!

2020-10-06 11:40 UTC, adybbroe commented
Ok to merge @mraspaud and @pnuu ?

2020-10-06 12:02 UTC, mraspaud commented
I don't see any tests, but I guess it's the rule in this package? If you are ok with that, then you can merge imo.

2020-10-06 12:04 UTC, adybbroe commented
> I don't see any tests, but I guess it's the rule in this package? If you are ok with that, then you can merge imo.

Yes, it is unfortunately the rule in this package. I can make an issue on that

2020-10-06 12:04 UTC, merged