Fix nwp prepare
pytroll/pytroll-pps-runner pull request #52
Opened 2022-05-11 08:50 UTC by ninahakansson

Be smarter when constructing the NWP files for PPS. Only include fields from the requirement file. Also don't use the name of fields as that can be slightly modified (Height => height). 

 - [ ] Closes #xxxx 
 - [ ] Tests added 
 - [ ] Tests passed: Passes ``pytest nwcsafpps_runner`` 
 - [X] Passes ``flake8 nwcsafpps_runner`` 
 - [ ] Fully documented

2022-05-12 15:25 UTC, adybbroe commented
Is it ready for review @ninahakansson ?
I see the test coverage went down a bit?

2022-05-12 15:30 UTC, adybbroe requested changes
Can you have a look of the codecov complaints and see if they can be adressed?

2022-05-12 15:30 UTC, adybbroe commented on nwcsafpps_runner/prepare_nwp.py
> +    srplines = [ll.strip('M ').strip('\n') for ll in lines if str(ll).startswith('M')]
These lines here are a bit cryptic. Wonder if it would be more clear if they were put in separate functions with meaningful names?

2022-09-28 13:12 UTC, adybbroe commented on nwcsafpps_runner/tests/test_nwp_prepare.py
> +# Copyright (c) 2021 Adam.Dybbroe
```suggestion
# Copyright (c) 2022 Pytroll Community
```

2022-09-28 13:16 UTC, adybbroe commented on nwcsafpps_runner/tests/test_nwp_prepare.py
> +# Author(s):
I think we should get rid of the Authors list in the headers and instead collect authors in an AUTHORS.md file like is done for Satpy and Pyspectral and other Pytroll projects. You could perhaps add an AUTHORS file and remove them here in the headers tha affect this PR at least?

2022-09-28 13:20 UTC, adybbroe commented on nwcsafpps_runner/prepare_nwp.py
> +    # tempfile.tempdir = nwp_outdir
Remove inline comment

2022-09-28 13:21 UTC, adybbroe commented on nwcsafpps_runner/prepare_nwp.py
> +        LOG.warning("tmp file %s gone! Cannot remove it...", filename)
Could that be tested?

2022-09-28 13:21 UTC, adybbroe commented on nwcsafpps_runner/prepare_nwp.py
> +            forecast_step = "{:03d}H{:02d}M".format(forecast_step.days * 24 + forecast_step.seconds / 3600, 0)
Could that be tested?

2022-09-28 13:22 UTC, adybbroe commented on nwcsafpps_runner/prepare_nwp.py
> +            remove_file(tmp_result_filename)
Is this tested?

2022-09-28 13:23 UTC, adybbroe commented on nwcsafpps_runner/prepare_nwp.py
> +    # Return 129 100 isobaricInhPa
Perhaps beter to add these comments to the function docstring.

2022-09-28 13:25 UTC, adybbroe reviewed
Very nice with the increased test coverage, thanks!
I have some comments, suggestions and questions. As testing before was really poor maybe you can defer further test coverage to the next PR on this code. But consider my few suggestions first,

2022-09-29 12:08 UTC, ninahakansson commented
I fixed most of the comments.

2022-09-29 12:48 UTC, adybbroe commented
@TAlonglong Could you have a quick look as well. I am quite happy and ready to merge now. Once we understand the failed tests above

2022-09-29 14:01 UTC, adybbroe commented
@ninahakansson 
https://conda-forge.org/docs/user/announcements.html#dropping-python-3-7
Time to drop 3.7 support? Otherwise we need to find another channel to get Python 3.7

2022-10-03 08:09 UTC, TAlonglong approved these changes
LGTM

2022-10-03 08:09 UTC, merged